### ISSUE TITLE
Create List-Component with Objects

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#1]
## Value statement - a requirement, not a solution
As a **user**
We want **a list of gas stations with prices and locations**
so that **we can see all important information in a list**

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-04-26 um 11 55 31](https://user-images.githubusercontent.com/100355993/165274497-4b9700c5-b906-4679-959b-d9cdca23e077.png)

## Acceptance criteria (functional descriptions)
- [x] The component renders a list of labels with gasstation-datas
- [x] The component renders a star (Favorite Button) which can clicked, and the label will be shown at the favorite page
- [x] If the star is clicked, the color will be changed to yellow.
- [x] The name of the gas station can be a maximum of 20 characters long.

## Tasks (to-dos for the team)
- [x] Write objects with gas station data.
- [x] Fetch datas from objects (price, name, street, postal code, city)
- [x] Create an unordered list.
- [x] Create a list of objects.

## Size
medium

**Comment by mpagels** [comment]
Hey guys, great start, but a lot of room for improvement here:

- Your `value statement` is misleading. Do the `user` needs data to display gas station data? This seems weird.
The user just needs a list that renders the data. 
- Statement should something like this:
```
As a user
I want a list of gas stations with prices and locations
so that I can see all important information in a list
```

- The `acceptance criterias` could be a lot more specific. 
- What kind of information to render, when the user accesses the app, for example.
- I see a `distance` value in the list items. Is this something to consider when building the component?
- the blue arrow, this looks like a button. Is this something to consider when building the component?
- I see that in the `design` the name of the `station` is shorten with `...` . Is this something to consider when building the component?

**Comment by D3nnis249** [comment]
Thank you for reading through and for the improvements. I will keep to the guidelines as we go forward.
