### ISSUE TITLE
Add map-page with POI´s

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#25]
## Value statement - a requirement, not a solution
As a **user** 
We need **a map-page** 
so that **we see the gas stations on a map with a Point of Interest** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-05-09 um 10 54 43](https://user-images.githubusercontent.com/100355993/167375700-99976ecf-18fa-4535-b135-1442de612ab9.png)

## Acceptance criteria (functional descriptions)
- [ ] all prices will show on a POI 
- [x]  you can change to the detailed Page onclick from the actual POI

## Tasks (to-dos for the team)
- [x] Add Nav Bar
- [x] Add Header
- [x] create Map page
- [x] create a MapBox-Card
- [x]  Add POI's
- [x] create logic to on click a redirect from the POI to the detailed page

## Size
Large
