### ISSUE TITLE
Add input field with filter method for PostalCodes and Cities

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#3]
## Value statement - a requirement, not a solution
As a **user** 
We need **an input field** 
so that **we can filter for cities and postal codes** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-04-25 um 18 37 03](https://user-images.githubusercontent.com/100355993/165134068-4ff2b572-41dd-4d5b-9c82-a69c7ca4c155.png)

## Acceptance criteria (functional descriptions)
- [ ] Filter for cities and postal codes.
- [ ] The logic starts onChange, 

## Tasks
- [ ] Add a form
- [ ] Add a label
- [ ] Add an input type text field
- [ ] Add a dropdown-menu
- [ ] Write a filter method to view all suitable gas-stations(postal code or cities)

## Size
medium

**Comment by mpagels** [comment]
Hey guys,
the name of the story is misleading. Do you want to filter in the story or do you want to build a simple `input` element?

Let's assume you want to filter a list:

- the `acceptance criterias` have too less of information: A fellow developer needs to know what happens, when the input is filled. Is a `submit` button needed, to start the `filter` logic or is the `filter` logic applied, when the input is changed. What is shown, when the little arrow is clicked and the dropdown is shown?

You should write a `story` this way, that you could give it to another developer and  he or she could code your vision of the feature without any further questions. Be detailed as possible what happens.
