### ISSUE TITLE
Create Error Page

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#39]
## Value statement - a requirement, not a solution
As a **user** 
We need a page to handle and catch errors
so that the app doesnt crash *

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-05-21 um 09 57 46](https://user-images.githubusercontent.com/100355993/169642027-e2ca31db-e897-4c60-ace5-cc7ce27aec9a.png)

## Acceptance criteria (functional descriptions)
- [ ] 

## Tasks (todos for the team)
- [x] Create a new page named PageNotFound.jsx
- [x] Add route to the new page with universal selector
- [x] If an error message comes back from the API (first 404, then 200) then an error is displayed. If only a 404 comes from the API, an error is also displayed and the page does not break.

## Size
 medium
