### ISSUE TITLE
Create Navigation Bar

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#4]
## Value statement - a requirement, not a solution
As a **user** 
We need **a navigation bar**
so that **we can go everywhere from all sites**

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-04-26 um 12 13 59](https://user-images.githubusercontent.com/100355993/165277933-c447adc5-bdaa-4c2a-bb20-0b062eead1a0.png)

## Acceptance criteria (functional descriptions)
- [x] 4 different pages: home, map, settings, favorites
- [x] Clickable color for the icons is #FF928B
- [x] The clicked Icon should be having an active color that  is #1B75BF
- [x] If an icon is clicked, the page will switch
- [x] Nav bar stays fixed while scrolling

## Tasks
- [x] Link every page to nav bar
- [x] Add CSS positioning

## Size
medium
