### ISSUE TITLE
Fetch from API

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#40]
## Value statement - a requirement, not a solution
As a **user** 
We need Data´s for our Page 
so that we can see the prices from the GasStations

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-05-21 um 10 15 30](https://user-images.githubusercontent.com/100355993/169642669-6a0727ce-e885-4610-b24e-807bd6b461d5.png)

## Acceptance criteria (functional descriptions)
- [x] fetch to get the Datas from the API

## Tasks (todos for the team)
- [x] Write a fetch to get the Datas from the API 
- [x] Display the cards with live datas on the pages

## Size
large
