### ISSUE TITLE
Add best price page

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#41]
## Value statement - a requirement, not a solution
As a **user** 
We need a page that shows us the best gas station in relation with the distance and the current prices
so that we geht the best price

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-05-21 um 10 24 23](https://user-images.githubusercontent.com/100355993/169643013-ce685016-b8b6-4c64-9efe-a14f8f6b7a07.jpeg)
## Acceptance criteria (functional descriptions)
- [ ] specify the maximum tank volume and the fuel consumption of the vehicle and the current fuellevel of the vehicle to get the best price in the area displayed
- [ ] can link to detailed page

## Tasks (todos for the team)
- [ ] Add header
- [ ] Add navBar
- [ ] Add route
- [ ] Add gasstation list with criterias 
- [ ] Add inputfield for position (type text)
- [ ] Add inputflied for volume in l (type number)
- [ ] Add inputfield for average consumption (L/100km, type number)

## Size
large
