### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#43]
## Value statement - a requirement, not a solution
As a Developer
We need to testing our components
so that so we can make sure our components always work

## Acceptance criteria (functional descriptions)
- [ ]  Methods and functions from React Testing Libary / Jest 

## Tasks (todos for the team)
- [ ] Install React testing libary / Jest
- [ ] write test for diffrent components

## Size
medium
