### ISSUE TITLE
Add Favorites to Local-Storage

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#5]
As a User
We need **the gas-stations to be saved**
so that **we are able to safe the Stations in the localStorage**

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-04-26 um 13 05 06](https://user-images.githubusercontent.com/100355993/165286673-5c5b03d1-7e7d-467d-aeb8-e8bb5f9fdcbd.png)
![Bildschirmfoto 2022-04-26 um 13 07 20](https://user-images.githubusercontent.com/100355993/165287044-6fd21b8c-3431-4fbe-b3f5-1ac8da2fa043.png)

## Acceptance criteria (functional descriptions)
- [x] OnClick save or remove the stations in the localStorage

## Tasks (to-dos for the team)
- [x]  Add a `favorite` button
- [x] When the station is not saved as a favorite yet, the button indicates that with another icon
- [x] When clicking the button, the station is saved as a favorite and the button indicates that with a yellow star icon
- [x] The yellow color is RGB #F1E800
- [x] When clicked again, the character is removed as a favorite, the icon changes again
- [x] The favorite state persists, when the app is reloaded. (localStorage)

## Size
medium
