### ISSUE TITLE
Add the favorite-page

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#6]
## Value statement - a requirement, not a solution
As a **user** 
We need **a favorite-page** 
to show **every saved favorite gas-station on a separate page** 

## Description (Text, Scribble, 
![Bildschirmfoto 2022-04-26 um 13 05 06](https://user-images.githubusercontent.com/100355993/165299020-b4764f74-ef98-43a4-a807-faee4ee4ea3f.png)
Wireframe, Design)

## Acceptance criteria (functional descriptions)

- [x] Show every as favorite marked gas-stations
- [x] Show header component

## Tasks (to-dos for the team)
- [x] The page should render all the saved favorite gas-stations
- [x] When clicked the favorite button, the gas-station should be removed from the array
- [x] The array should update in the localStorage as well
- [x] Add the link to `favorite page` in the `NavBar` component
- [x] Add NavBar connection

## Size
medium
