### ISSUE TITLE
Add the detailed-page

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#8]
## Value statement - a requirement, not a solution
As a **user** 
We need **a detailed-page** 
so that **we see only one gas-station with more details** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-04-26 um 14 42 00](https://user-images.githubusercontent.com/100355993/165302249-73149379-3d42-47e6-bedb-eb1536b0e982.png)

## Acceptance criteria (functional descriptions)
- [x] all prices, the name and the location will show on one page for only one gas-station
- [x] you can change to all pages from the detailed-page
- [x] Show header component

## Tasks (to-dos for the team)
- [x] Add Nav Bar
- [x] install react-router
- [x] create gas-station page
- [x] create a detailed gas-station card with Opening hours and list elements that include the prices 
- [x] create logic, when clicking the list element of gas-station on the landing page, the user is moved to the detailed page and the gas-station is loaded with more details

## Size
medium
