### ISSUE TITLE
Add the settings-page

### ISSUE THREAD

**Issue by D3nnis249** [D3nnis249/GenialTanken-Capstone#9]
## Value statement - a requirement, not a solution
As a **user** 
We need **a settings-page** 
 to **select our type of fuel and the radius of gas-stations** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2022-04-26 um 14 59 35](https://user-images.githubusercontent.com/100355993/165305376-95dc4a9c-cb6f-473f-83c1-4043958335be.png)

## Acceptance criteria (functional descriptions)
- [x] You can change to all pages from the settings-page
- [x] You can choose your fuel with checkboxes (only one can be selected).
- [ ] You can choose the radius in which you want to display the gas stations (max 25 km).

## Tasks (to-dos for the team)
- [x] Add header component
- [x] Create Headline "Kraftstoff"
- [x] Create fuel components (e5, e10, diesel) with checkboxes (only one can be selected).
- [x] Create Headline "Radius"
- [x] Create slider (input type="range").
- [x] Add the link to `settings page` in the `NavBar` component
- [x] Add NavBar connection

## Size
medium-large
